#!/bin/env php
<?php

require 'vendor/autoload.php';

use \Bunny\HomeBank\HomeBankFile;
use \Bunny\HomeBank\TypeParser;
use \Bunny\HomeBank\NodeParser;

// Parse command line options
$options  = getopt( 'f:' );
$filename = ( !empty( $options['f'] ) ) ? $options['f'] : '';

if ( empty( $filename ) )
{
    getUsage( $argv[0] );
}

if ( ! is_readable( $filename ) )
{
    echo "Error: Could not read HomeBank data file.\n";
}

// Create DOM Document, load and parse HomeBank data file
$dom = new DOMDocument();
$dom->load( $filename );

$homebank = new HomeBankFile( $dom, new TypeParser(), new NodeParser() );
$accounts = $homebank->getAccounts();
$entries  = $homebank->getEntries();

// Initialize Twig Template Engine
$loader = new Twig_Loader_Filesystem( './templates'  );
$twig   = new Twig_Environment( $loader );

// Opening balances will be entered as 1/1 in the year of the first entry
$start_date = date( 'Y', strtotime( $entries[0]['date'] ) ) . '/01/01';

// Output results in ledger format
echo $twig->render( 'opening_balances.twig', array( 'accounts' => $accounts, 'date' => $start_date ) );
echo $twig->render( 'entries.twig', array( 'entries' => $entries ) );

function getUsage( $name )
{
    echo "usage: " , $name , " -f input_file" , "\n";
    echo "  options: \n";
    echo "    -f         HomeBank .xhb data filename \n";
    echo "\n";
    exit;
}

