#!/bin/env php
<?php

require 'vendor/autoload.php';

use \Bunny\HomeBank\HomeBankFile;
use \Bunny\HomeBank\TypeParser;
use \Bunny\HomeBank\NodeParser;

$options  = getopt( 'f:' );
$filename = ( !empty( $options['f'] ) ) ? $options['f'] : '';

if ( empty( $filename ) )
{
    getUsage( $argv[0] );
}

if ( ! is_readable( $filename ) )
{
    echo "Error: Could not read HomeBank data file.\n";
}

$dom = new DOMDocument();
$dom->load( $filename );

$homebank   = new HomeBankFile( $dom, new TypeParser(), new NodeParser() );
$accounts   = $homebank->getAccounts();
$payees     = $homebank->getPayees();
$categories = $homebank->getCategories();
$entries    = $homebank->getEntries();

foreach ( $accounts as $account )
{
    if ( (int)$account['initial'] != 0 )
    {
        echo "1/1 * Opening Balance\n";
        echo "    " . $account['account_type'] . ":" . $account['name'] . "    ". $account['initial'] . "\n";
        echo "    Equity:Opening Balances\n";
        echo "\n";
    }
}

foreach ( $entries as $entry )
{
    if ( empty( $entry['category'] ) )
        $category = 'Uncategorized';
    else
        $category = $categories[ $entry['category'] ][ 'full_name' ];

    if ( $entry['amount'] > 0 )
    {
        $entry_type = 'Income';
    }
    else
    {
        $entry_type = 'Expenses';
    }

    if ( empty( $entry['payee'] ) )
        $payee = 'Unknown Payee';
    else
        $payee = $payees[ $entry['payee'] ]['name'];

    // Date
    echo $entry[ 'date' ];

    // Recon Flag
    echo ( $entry[ 'reconciled' ] ) ? ' * ' : '   ';

    // Payee
    echo $payee . "\n";

    // Description if available
    if ( !empty( $entry['wording'] ) )
        echo '    ; ' . str_replace(array('[',']'), '|', $entry['wording']) . "\n";

    // Payment line
    echo '    ' , $entry_type , ':' , $category , '     ' , ( $entry['amount'] * -1 );

    // Info if available
    if ( !empty( $entry['info'] ) )
        echo "     ; " . $entry['info'];

    echo "\n";

    // Account line
    echo '    ' , $accounts[ $entry['account'] ][ 'account_type' ] , ':' , $accounts[ $entry['account'] ]["name"] , "\n";
    echo "\n";
}


function getUsage( $name )
{
    echo "usage: " , $name , " -f input_file" , "\n";
    echo "  options: \n";
    echo "    -f         HomeBank .xhb data filename \n";
    echo "\n";
    exit;
}

