#!/bin/env php
<?php

require 'vendor/autoload.php';

use \Bunny\HomeBank\HomeBankFile;
use \Bunny\HomeBank\TypeParser;

$options  = getopt( 'f:' );
$filename = ( !empty( $options['f'] ) ) ? $options['f'] : '';

if ( empty( $filename ) )
{
    getUsage( $argv[0] );
}

if ( ! is_readable( $filename ) )
{
    echo "Error: Could not read HomeBank data file.\n";
}

$dom = new DOMDocument();
$dom->load( $filename );

$homebank   = new HomeBankFile( $dom, new TypeParser() );
$accounts   = $homebank->getAccounts();
$payees     = $homebank->getPayees();
$categories = $homebank->getPayees();
$entries    = $homebank->getEntries();

foreach ( $accounts as $account )
{
    if ( (int)$account['initial'] != 0 )
    {
        if ( $account['key'] == 5 )
            $a_type = 'Liabilities';
        else
            $a_type = 'Assets';

        echo "1/1 * Opening Balance\n";
        echo "    " . $a_type . ":" . $account['name'] . "    ". round( $account['initial'], 2 ) . "\n";
        echo "    Equity:Opening Balances\n";
        echo "\n";
    }
}

foreach ( $entries as $entry )
{
    $reconciled = false;

    if ( isset( $entry['flags'] ) )
    {
        $reconciled = (bool)( (int)$entry['flags'] & 1 );
    }

    if ( empty( $entry['category'] ) )
        $category = 'Uncategorized';
    else
        $category = getCategoryString( $entry['category'], '' );

    if ( $entry['amount'] > 0 )
    {
        $entry_type = 'Income';
    }
    else
    {
        $entry_type = 'Expenses';
    }

    if ( $entry['account'] == 5 )
        $a_type = 'Liabilities:';
    else
        $a_type = 'Assets:';

    if ( empty( $entry['payee'] ) )
        $payee = 'Unknown Payee';
    else
        $payee = $payees[ $entry['payee'] ]['name'];

    // Date
    echo $entry[ 'date' ];

    // Recon Flag
    echo ( $reconciled ) ? ' * ' : '   ';

    // Payee
    echo $payee . "\n";

    // Description if available
    if ( !empty( $entry['wording'] ) )
        echo '    ; ' . str_replace(array('[',']'), '|', $entry['wording']) . "\n";

    // Payment line
    echo '    ' , $entry_type , ':' , $category , '     ' , ( round( $entry['amount'], 2 ) * -1 );

    // Info if available
    if ( !empty( $entry['info'] ) )
        echo "     ; " . $entry['info'];

    echo "\n";

    // Account line
    echo '    ' , $a_type , $accounts[ $entry['account'] ]["name"] , "\n";
    echo "\n";
}


function getUsage( $name )
{
    echo "usage: " , $name , " -f input_file" , "\n";
    echo "  options: \n";
    echo "    -f         HomeBank .xhb data filename \n";
    echo "\n";
    exit;
}


function getCategoryString( $cat_id, $desc )
{
    global $categories;

    if ( !isset( $categories[ $cat_id ] ) )
    {
        return 'Uncategorized';
    }

    if ( !isset( $categories[ $cat_id]['parent'] ) )
    {
        if ( empty( $desc ) )
        {
            return $categories[ $cat_id ]['name'];
        }
        else
        {
            return $categories[ $cat_id ]['name'] . ':' . $desc;
        }
    }

    return getCategoryString( $categories[ $cat_id ]['parent'], $categories[ $cat_id ]['name'] );
}

